# Generated by Django 4.2.7 on 2023-11-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="image",
            field=models.CharField(max_length=50),
        ),
    ]
