# Generated by Django 4.2.7 on 2023-11-04 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_pizza_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="image",
            field=models.CharField(
                max_length=500,
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[django.core.validators.MaxLengthValidator(limit_value=50)],
            ),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="price",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ]
            ),
        ),
    ]
